#!/bin/sh
# macos-sign-runner.sh — `tauri dev|build --runner`로 쓰는 cargo 대리자.
#
# cargo를 그대로 부르고, `cargo build`가 성공하면 앱(iyagi-app)과 데몬
# (iyagi-termd) 실행 파일을 로컬 인증서(IYAGI_SIGNING_IDENTITY)로 다시 서명한다.
# scripts/tauri.mjs가 macOS에서 그 인증서를 찾았을 때만 이 runner를 넘긴다.
#
# 왜 여기서: `tauri dev`는 번들 없이 target/<profile>/iyagi-app을 곧바로
# 띄운다 — 빌드와 실행 사이에 서명을 끼울 곳이 runner뿐이다. ad-hoc 서명은
# 빌드마다 바뀌어 macOS 권한(TCC)이 매번 새 앱으로 여기고 다시 묻는다.
#
# 실행 중인 파일을 제자리에서 다시 서명하면 커널이 그 프로세스를 죽일 수 있어
# (코드 페이지 서명 불일치) 복제본(cp -c, APFS clone)에 서명한 뒤 mv로 바꾼다.
# 서명 실패는 경고만 하고 빌드는 성공으로 둔다 — 서명은 권한 창을 줄이는
# 편의이지 빌드 조건이 아니다.
#
# dev(IYAGI_DEV_APP_NAME이 있을 때 — scripts/tauri.mjs가 `tauri dev`에서만 넘긴다)는
# 서명 뒤에 실행 파일을 `<이름>.app`으로 감싼다. 번들 밖에서 뜬 실행 파일은
# Info.plist를 품고 있어도 Dock이 파일 이름(`iyagi-app`)으로 보여 준다 — 번들
# 경로로 exec돼야 제품 이름이 나온다(심볼릭 링크로는 안 된다). 그래서
# target/<profile>/iyagi-app 자리에는 번들 안의 실행 파일을 exec하는 작은
# 스크립트를 둔다. `tauri dev`는 그 경로를 그대로 띄우고, exec라 pid도 같다.

if [ "${1:-}" != "build" ] || [ "$(uname -s)" != "Darwin" ] ||
  { [ -z "${IYAGI_SIGNING_IDENTITY:-}" ] && [ -z "${IYAGI_DEV_APP_NAME:-}" ]; }; then
  exec cargo "$@"
fi

cargo "$@" || exit $?

profile=debug
triple=
expect=
for arg in "$@"; do
  if [ -n "$expect" ]; then
    case "$expect" in
      profile) profile=$arg ;;
      target) triple=$arg ;;
    esac
    expect=
    continue
  fi
  case "$arg" in
    --) break ;;
    --release | -r) profile=release ;;
    --profile) expect=profile ;;
    --profile=*) profile=${arg#--profile=} ;;
    --target) expect=target ;;
    --target=*) triple=${arg#--target=} ;;
  esac
done
[ "$profile" = dev ] && profile=debug

root=$(cd "$(dirname "$0")/.." && pwd)
target_dir=${CARGO_TARGET_DIR:-$root/target}
case "$target_dir" in
  /*) ;;
  *) target_dir=$PWD/$target_dir ;;
esac
out=$target_dir/${triple:+$triple/}$profile

sign() {
  file=$1
  identifier=$2
  [ -f "$file" ] || return 0
  tmp=$file.iyagi-signing
  rm -f "$tmp"
  if { cp -c "$file" "$tmp" 2>/dev/null || cp "$file" "$tmp"; } &&
    codesign --force --sign "$IYAGI_SIGNING_IDENTITY" --identifier "$identifier" "$tmp" 2>/dev/null &&
    mv -f "$tmp" "$file"; then
    echo "macos-sign-runner: signed ${file##*/} as $identifier with \"$IYAGI_SIGNING_IDENTITY\"" >&2
    return 0
  fi
  rm -f "$tmp"
  echo "macos-sign-runner: warning: could not sign $file — it keeps its ad-hoc signature" >&2
}

# 홑따옴표 인용 — 생성하는 스크립트에 공백이 든 경로(앱 이름)를 박는다.
quote() {
  printf "'%s'" "$(printf '%s' "$1" | sed "s/'/'\\\\''/g")"
}

wrap_dev_app() {
  bin=$out/iyagi-app
  [ -f "$bin" ] || return 0
  # 지난 dev가 남긴 스크립트 그대로다(cargo가 실행 파일을 다시 내놓지 않음) — 번들도 최신.
  if [ "$(head -c 2 "$bin")" = "#!" ]; then
    return 0
  fi
  app=$out/$IYAGI_DEV_APP_NAME.app
  exe=$app/Contents/MacOS/iyagi-app
  mkdir -p "$app/Contents/MacOS" "$app/Contents/Resources" || return 1
  cp "$root/src-tauri/icons/icon.icns" "$app/Contents/Resources/icon.icns" 2>/dev/null
  cat >"$app/Contents/Info.plist" <<PLIST || return 1
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleName</key><string>$IYAGI_DEV_APP_NAME</string>
  <key>CFBundleDisplayName</key><string>$IYAGI_DEV_APP_NAME</string>
  <key>CFBundleIdentifier</key><string>${IYAGI_DEV_APP_ID:-ai.iyagi.term}</string>
  <key>CFBundleExecutable</key><string>iyagi-app</string>
  <key>CFBundleIconFile</key><string>icon</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>NSHighResolutionCapable</key><true/>
</dict>
</plist>
PLIST
  # 서명된 실행 파일을 그대로 옮긴다(APFS clone이면 복사 비용도 없다).
  { cp -c "$bin" "$exe.tmp" 2>/dev/null || cp "$bin" "$exe.tmp"; } && mv -f "$exe.tmp" "$exe" || return 1
  # 데몬은 계속 target/<profile>/iyagi-termd를 쓴다 — 앱의 current_exe가 번들 안으로
  # 옮겨 가면 "실행 파일 옆" 후보가 사라지므로 명시한다(사용자가 정한 값은 존중).
  {
    printf '#!/bin/sh\n'
    printf '# Generated by scripts/macos-sign-runner.sh (tauri dev): run the app from its .app wrapper.\n'
    printf '[ -n "${IYAGI_TERMD_PATH:-}" ] || IYAGI_TERMD_PATH=%s\n' "$(quote "$out/iyagi-termd")"
    printf 'export IYAGI_TERMD_PATH\n'
    printf 'exec %s "$@"\n' "$(quote "$exe")"
  } >"$bin.tmp" && chmod 755 "$bin.tmp" && mv -f "$bin.tmp" "$bin"
}

if [ -n "${IYAGI_SIGNING_IDENTITY:-}" ]; then
  sign "$out/iyagi-app" ai.iyagi.term
  sign "$out/iyagi-termd" iyagi-termd
fi
if [ -n "${IYAGI_DEV_APP_NAME:-}" ] && ! wrap_dev_app; then
  echo "macos-sign-runner: warning: could not wrap the dev app in \"$IYAGI_DEV_APP_NAME.app\" — the Dock shows iyagi-app" >&2
fi
exit 0
